services:
  app:
    build: .
    container_name: CAREFLOW
    restart: always
    ports:
      - "3000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://localhost:27017/blogDB
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
    depends_on:
      - mongo

volumes:
  mongo_data:
